# Balanced Policy Template  
# Reasonable security with good usability for most use cases
version: "1.0"
name: "balanced-template"
description: "Balanced policy with reasonable security and usability"

locale: "en"
min_entity_length: 1

# Default to partial masking for better readability
default_strategy:
  kind: "partial"
  parameters:
    visible_chars: 3
    position: "start"
    mask_char: "*"
    preserve_delimiters: true

# Moderate confidence thresholds
thresholds:
  PERSON: 0.7
  EMAIL_ADDRESS: 0.7
  PHONE_NUMBER: 0.8
  CREDIT_CARD: 0.8
  US_SSN: 0.8
  IBAN_CODE: 0.7
  IP_ADDRESS: 0.6
  URL: 0.6
  MEDICAL_LICENSE: 0.8
  US_PASSPORT: 0.8
  US_DRIVER_LICENSE: 0.7

# Balanced per-entity strategies
per_entity:
  PERSON:
    kind: "hash"
    parameters:
      algorithm: "sha256"
      truncate: 8
      prefix: "NAME_"
      per_entity_salt:
        PERSON: "person_salt_v1"
    threshold: 0.7
    enabled: true
    
  EMAIL_ADDRESS:
    kind: "partial"
    parameters:
      visible_chars: 3
      position: "start"
      format_aware: true
      preserve_delimiters: true
      deterministic: true
    threshold: 0.7
    enabled: true
    
  PHONE_NUMBER:
    kind: "partial" 
    parameters:
      visible_chars: 4
      position: "end"
      format_aware: true
      preserve_delimiters: true
      deterministic: true
    threshold: 0.8
    enabled: true
    
  CREDIT_CARD:
    kind: "partial"
    parameters:
      visible_chars: 4
      position: "end"
      format_aware: true
      preserve_delimiters: true
      deterministic: true
    threshold: 0.8
    enabled: true
    
  US_SSN:
    kind: "partial"
    parameters:
      visible_chars: 4
      position: "end"
      format_aware: true
      preserve_delimiters: true
      deterministic: true
    threshold: 0.8
    enabled: true
    
  IP_ADDRESS:
    kind: "partial"
    parameters:
      visible_chars: 3
      position: "start"
      preserve_delimiters: true
    threshold: 0.6
    enabled: true
    
  URL:
    kind: "partial"
    parameters:
      visible_chars: 10
      position: "start" 
      preserve_delimiters: true
    threshold: 0.6
    enabled: true

# Context rules that balance security and usability
context_rules:
  heading:
    enabled: false  # Preserve document structure
    
  table:
    enabled: true
    threshold_overrides:
      PERSON: 0.8  # Higher threshold in tables
      
  footer:
    enabled: true
    
  header: 
    enabled: false  # Preserve document structure
    
  paragraph:
    enabled: true

# Default empty lists
allow_list: []
deny_list: []

# Policy composition settings
policy_composition:
  merge_strategy: "override"
  validation_level: "warn"